Dot com updates
umuthopeyildirim/FlatironOpenSource pull request #44
Opened 2023-01-18 13:26 UTC by igottheim

Based on issue #43 completion.

Description:
Get the flatironopensource.com domain name and connect new domain to Cloudflare.

 Add new domain  (flatironopensource.com) to:
 Cloudflare Pages.
 Cloudflare R2.
 Cloudflare Workers.

 Change React script to request lessons from .com instead of .ml.
 Change README with correct links.
 Create a Privacy page.
 Add GDPR notification for Google Analytics reason.
 Change Workers CORS settings to flatironopensource.com only.

2023-01-18 15:54 UTC, umuthopeyildirim requested changes
Please fix the commented stuff.

2023-01-18 15:54 UTC, umuthopeyildirim commented on main.py
> +envValue = requests.get('https://workers.flatironopensource.co/course/pd-prep')
Typo

2023-01-18 15:54 UTC, umuthopeyildirim commented on public/sitemap.xml
>      <lastmod>2022-12-29T21:32:17+00:00</lastmod>
You also need to add new legal pages

2023-01-18 15:54 UTC, umuthopeyildirim commented on sitemap.xml
> +  </url>
you also need to add new legal pages

2023-01-18 15:54 UTC, umuthopeyildirim commented on src/views/Landing.jsx
> +  alert("Please know that we use Google Analytics and cookies to track user traffic for this site. By clicking ok, you consent to flatironopensource.com's Cookie and Privacy policies.")
Instead of `Alert` we should use daisyUI modal.
https://react.daisyui.com/?path=/story/actions-modal--default

2023-01-18 15:54 UTC, umuthopeyildirim commented on src/views/Landing.jsx
> +     {!localStorage.getItem("alertOn")? setAlerts(): null}
we should rename that to `consent`

2023-01-18 18:31 UTC, igottheim commented on main.py
> +envValue = requests.get('https://workers.flatironopensource.co/course/pd-prep')
I fixed if we need for future use, but this is only for the output files. Good catch

2023-01-18 18:35 UTC, igottheim commented on public/sitemap.xml
>      <lastmod>2022-12-29T21:32:17+00:00</lastmod>
added legal, privacy, ters

2023-01-18 18:36 UTC, igottheim commented on sitemap.xml
> +  </url>
done

2023-01-19 11:18 UTC, umuthopeyildirim approved these changes
LGTM!

2023-01-19 11:19 UTC, merged